name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  packages: write
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./MCP.Extensions
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      working-directory: MCP.Extensions
      run: dotnet restore
    - name: Set package version
      id: vars
      run: echo "PACKAGE_VERSION=0.0.1-preview.${{ github.run_id }}" >> $GITHUB_ENV
    - name: Pack
      run: dotnet pack MCP.Extensions.csproj --configuration Release -p:PackageVersion=${{ env.PACKAGE_VERSION }} --no-restore --output ./nupkg
    - name: Publish to GitHub Packages
      run: |
        dotnet nuget add source --username echapmanFromBunnings --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/echapmanFromBunnings/index.json"
        dotnet nuget push ./nupkg/*.nupkg --source "github" --api-key ${{ secrets.GITHUB_TOKEN }}
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true
    - name: Publish to NuGet.org
      run: dotnet nuget push ./nupkg/*.nupkg --source "https://api.nuget.org/v3/index.json" --api-key ${{ secrets.NUGET_API_KEY }}
      continue-on-error: true
    - name: Clean up
      run: rm -r ./nupkg
  
